config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'gallery_analytics#home', as: :home
  post 'gallery_analytics/parse_gallery_log', as: :parse_gallery_log
  resources :gallery_analytics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log_file.rb
class LogFile < ApplicationRecord
  has_many :rooms
  has_many :visitors

  def self.parse_file(file)

    content_type = file.content_type
    #validating file content type
    if content_type == 'text/plain' || content_type == 'text/csv'

      #opening uploaded file
      file_pointer = File.open file.path

      #counting how much line to be parsed
      number_of_lines = file_pointer.readline

      log_hash = {}

      #loop to iterate over the lines
      number_of_lines.to_i.times do

        #reading log file line
        room_log = file_pointer.readline

        #splits log entry by space
        room_log_arr = room_log.split(' ')

        #assigning log value to respective variables
        visitor = room_log_arr[0].to_i
        room = room_log_arr[1].to_i
        status = room_log_arr[2]
        timestamp = room_log_arr[3].to_i

        stay = 0

        #checking if visitor key available in hash
        if log_hash.key?(visitor)
          #checking if room key available in visitory hash
          if log_hash[visitor].key?(room)
            #checking the status of visitor and calculating stay of visitor
            if log_hash[visitor][room][:status] == 'I'
              stay = timestamp - log_hash[visitor][room][:timestamp]
            elsif log_hash[visitor][room][:status] == 'O'
              stay = log_hash[visitor][room][:timestamp] - timestamp
            end

            #incrementing room count of visitor, stay and average stay
            log_hash[visitor][:room_count] += 1
            log_hash[visitor][:stay] += stay
            log_hash[visitor][:average_stay] = log_hash[visitor][:stay] / log_hash[visitor][:room_count]

          end

          log_hash[visitor][room] = {
              status: status,
              timestamp: timestamp,
              stay: stay
          }
        else
          #initiating hash for visitor
          log_hash[visitor] = {
              room => {
                  status: status,
                  timestamp: timestamp,
                  stay: stay
              },
              average_stay: 0,
              room_count: 0,
              stay: 0
          }
        end
      end
      #closing file
      file_pointer.close
      log_hash

    else
      return false
    end
  end

  #saving parsed result to database
  def save_parsed_result(log_hash)
    log_hash.each do |visitor_id, visitor_hash|
      Visitor.create_entry(self.id, visitor_id, visitor_hash)
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :log_file
  has_many :visits
  has_many :visitors, through: :visits
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :visitor
  belongs_to :room
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :log_file
  has_many :visits
  has_many :rooms, through: :visits

  def self.create_entry(log_file_id, visitor_id, visitor_hash)
    self.create(visitor_id: visitor_id,
                room_visits: visitor_hash[:room_count],
                average_stay: visitor_hash[:average_stay],
                log_file_id: log_file_id
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gallery_analytics_controller.rb
class GalleryAnalyticsController < ApplicationController
  def home

  end

  def parse_gallery_log

    #parsing uploaded file
    parsed_result = LogFile.parse_file(params[:file])

    if parsed_result
      name = params[:file].original_filename
      content_type = params[:file].content_type
      #creating log entry in table
      log_file = LogFile.create(name: name, content_type: content_type)
      log_file.save_parsed_result(parsed_result)
    else
      flash[:error] =  "Upload text or csv file"
      redirect_to home_path
      return
    end
    redirect_to gallery_analytics_path

=begin
    file = File.open params[:file].path
    number_of_lines = file.readline
    @log_hash = {}
    number_of_lines.to_i.times do
      room_log = file.readline
      room_log_arr = room_log.split(' ')
      room_log_arr[3] = room_log_arr[3].to_i
      stay = 0

      if @log_hash.key?(room_log_arr[1])
        if @log_hash[room_log_arr[1]].key?(room_log_arr[0])
          if @log_hash[room_log_arr[1]][room_log_arr[0]][:status] == 'I'
            stay =  room_log_arr[3] - @log_hash[room_log_arr[1]][room_log_arr[0]][:timestamp]
          elsif @log_hash[room_log_arr[1]][room_log_arr[0]][:status] == 'O'
            stay =  @log_hash[room_log_arr[1]][room_log_arr[0]][:timestamp] - room_log_arr[3]
          end
          @log_hash[room_log_arr[1]][:visitor_count] += 1
          @log_hash[room_log_arr[1]][:stay] += stay
          @log_hash[room_log_arr[1]][:average_stay] = @log_hash[room_log_arr[1]][:stay] / @log_hash[room_log_arr[1]][:visitor_count]

        end

        @log_hash[room_log_arr[1]][room_log_arr[0]] = {
            status: room_log_arr[2],
            timestamp: room_log_arr[3],
            stay: stay
        }
      else
        @log_hash[room_log_arr[1]] = {
            room_log_arr[0] => {
                status: room_log_arr[2],
                timestamp: room_log_arr[3],
                stay: stay
            },
            average_stay: 0,
            visitor_count: 0,
            stay: 0
        }
      end
    end
    file.close
=end

  end

  def index
    @log_files  = LogFile.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @log_file = LogFile.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_analytics_helper.rb
module GalleryAnalyticsHelper
end

app/views/gallery_analytics/home.html.erb
<h1><%= flash[:error] %></h1>
<%= form_tag parse_gallery_log_path, { :multipart => true } do %>
    <p>

      <label class="custom-file">
        <%= file_field_tag 'file', class: "custom-file-input" %>
        <span class="custom-file-control"></span>
      </label>
    </p>
    <p>
      <%= submit_tag "Upload" %>
    </p>
<% end %>

app/views/gallery_analytics/index.html.erb
<div class="container">
  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>action</th>
    </tr>
    </thead>
    <tbody>
    <% @log_files.each do |log_file| %>
        <tr>
          <td>
            <%= log_file.id %>
          </td>
          <td>
            <%= log_file.name %>
          </td>
          <td>
            <%= link_to "Result", gallery_analytic_path(log_file.id) %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <div class="flickr_pagination">
    <%= will_paginate @log_files %>
  </div>
</div>

app/views/gallery_analytics/show.html.erb
<div class="container">
  <table class="table table-striped table-bordered">
    <thead class="thead-default">
    <tr>
      <th>visitor id</th>
      <th>room visits</th>
      <th>average stay</th>
    </tr>
    </thead>
    <tbody>
    <% @log_file.visitors.each do |visitor| %>
        <tr>
          <td>
            <%= visitor.visitor_id %>
          </td>
          <td>
            <%= visitor.room_visits %>
          </td>
          <td>
            <%= visitor.average_stay %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtGallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>